@user = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI4NTYwNjd9.bolxa6fNnlHWLTushJK-QWx2RijeEaEFQdtOvSk7070
# {{user}} is how to interpolate

### Actors Index Action
GET http://localhost:3000/actors.json

### Actos Show Action
GET http://localhost:3000/actors/10.json

### Actors Create Action
POST  http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Anybody",
  "last_name": "Something",
  "known_for": "a thing"
}

### Actors Update Action
PATCH  http://localhost:3000/actors/28.json
Content-Type: application/json

{
  "first_name": "elijah",
  "last_name": "woods",
  "known_for": "lord of the flies"
}

### Actors Destroy Action
DELETE  http://localhost:3000/actors/20.json

# -----------------------------------------------

### Movies Index Action
GET http://localhost:3000/movies.json

### Movies Show Action
GET http://localhost:3000/movies/2.json

### Movies Create Action
POST http://localhost:3000/movies.json
Content-Type: application/json

{
"title": "test title 2",
"year": 2000,
"plot": "test plot"
}

### Movies Update Action
PATCH http://localhost:3000/movies/6.json 
Content-Type: application/json

{
"title": "not test title"
}

### Movies Delete Action
DELETE http://localhost:3000/movies/5.json 

### User Create Action
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Sedol",
  "email": "Sedol@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions Create Action
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "bob@test.com",
  "password": "password"
}
